version: '3'

services:
  app:
    build:
      dockerfile: "./package/Dockerfile"
      context: ".."
    environment:
      - CONFIG_FILE=/configs/config.yml
    volumes:
      - ../configs:/configs:ro
      - app-apis:/app/static/apis:rw
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - app

volumes:
  app-apis:
